### ISSUE TITLE
Воруем параметры функций

### ISSUE THREAD

**Issue by Sazoks** [redb0/python-bp#4]
Т.к. списки в Python - изменяемый типа данных, то при передаче списка в функцию исходный список будет изменен, если в этой ф-ии, к примеру, мы добавляли какие элементы, т.е.:
```
def f(a: list):
    a.append(1)


def main():
    a = []
    print(a)
    f(a)
    print(a)


if name == "main":
    main()
```
Вывод будет такой:
```
[]
[1]
```

Но! Внезапно следующий код также сработает:
```
def f(a=[]):
    a.append(1)
    print(a)


def main():
    f()
    f()
    f()
    

if __name__ == "__main__":
    main()
```
Вывод:
```
[1]
[1, 1]
[1, 1, 1]
```

Как же так? По умолчанию мы принимаем пустой список в функцию f, но этого списка нигде, кроме текущей функции, нет. Однако с каждом выводом список дополняется новыми элементами. 
Дело в том, как я понял из своих наблюдений, что память под параметры функций выделяется в глобальной области видимости. Доказывает это следующий код:
```
import ctypes


def f(a=[]):
    a.append(1)
    print(a)
    return id(a)


def main():
    m_id = f()
    f()
    f()

    a = ctypes.cast(m_id, ctypes.py_object).value
    print(a)


if __name__ == '__main__':
    main()
```

Здесь мы вернули из ф-ии id списка (к слову, при любом такой вызове функции id этого пустого списка будет один и тот же). Затем вызвали функцию несколько раз. После этого в переменную a с помощью модуля ctypes и преобразований типов я получил значение по этому id. На удивление, вывод будет следующий:
```
[1]
[1, 1]
[1, 1, 1]
[1, 1, 1] # Это выводит строка print(a)
```

Однако такой забавный способ работает только с параметрами по умолчанию, т.к. они сохраняются в f.__defaults__ и ссылка на эти объекты хранится в этом свойстве функции.

**Comment by redb0** [comment]
## Оформление
Для выделения ```кода``` прямо внутри строки пользуйтесь специальной разметкой ```` `код` ````. Без разметки некоторые символы могут восприниматься как разметка markdown, например, __defaults__, а должно быть `__defaults__`. Кроме этого, для подсветки кода на github нужно указывать язык сразу после открывающих апострофов. 

## Комментарии к примеру
Что касается выделения памяти. На самом деле память выделяется не в глобальной области видимости, т.к. в `globals()` переменной `a` не будет.
Например, если создать генератор:
```python
def foo():
     bar = 42
     print(f'{id(bar) = }')
     yield id(bar)
     print('End')
```
До начала выполнения функции в `globals()` будет только функция `foo`. После выполнения следующей строки:
```python
baz = foo()
next(baz)
```
Переменной `bar` не окажется в глобальной области видимости, хотя генератор еще не завершен. Тем не менее получить доступ по `id` можно без проблем:

```python
import ctypes
ctypes.cast(1778100800, ctypes.py_object).value  # использовать id из принта
```

Здесь мы получили доступ к области памяти генератора. Точно также работает и ваш пример.

Исправьте описание и можете реализовать этот пример в соответствующем файле https://github.com/redb0/python-bp/blob/master/python_pd/badcode.ipynb. Сделайте коммит в новую ветку и предложите изменения через pull request в соответствии с правилами https://github.com/redb0/python-bp/blob/master/CONTRIBUTING.md.
