### ISSUE TITLE
Переименовать файлы .md на README.md

### ISSUE THREAD

**Issue by AsakoKabe** [redb0/python-bp#5]
1. Файл python-bp/python_pd/work/syntax/overview.md лучше переименовать в README.md, чтобы файл нормально отображался в github.
2. Ну и в файлу python-bp/CONTRIBUTING.md изменить описание(49 строка). При добавлении задания в папке должен лежать файл не description.md, а README.md, так же для корректного отображения в github. 
3. Переименовать python-bp/python_pd/work/syntax/fizzbuzz/description.md на README.md по причинам, указанным выше.

**Comment by redb0** [comment]
Выполнено в pull request #6
